### ISSUE TITLE
[13.0] account_invoice_tax: Taxes not applied

### ISSUE THREAD

**Issue by sgheller** [ingadhoc/account-invoicing#107]
Impacted versions:
 
 - 13.0
 
Steps to reproduce:
 
https://user-images.githubusercontent.com/50003794/111487164-e2db8680-8716-11eb-9f1f-8703af051b26.mp4

- Se carga el impuesto a través del wizard
- Al hacer algún cambio en las lineas aparece el valor del impuesto
- Cuando el valor aparece no es el que se cargó desde el wizard

**Comment by jjscarafia** [comment]
probablemente tenga que ver con un cambio en odoo que revertimos en este pr https://github.com/odoo/odoo/pull/67632
revirtiendo eso funciona?

**Comment by sgheller** [comment]
Parece que sí, queda esperando el merge resolviendo. Gracias Juan José.
